package com.mercado_challenge.MercadoAdventure.domain.model;

import java.util.List;

import com.mercado_challenge.MercadoAdventure.application.port.in.command.OrderCreationCommand;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Order {
    private String orderId;
    private String userId;
    private List<OrderItem> items;
    private Double totalAmount;
    private OrderStatus status;

    public static Order createFromCommand(OrderCreationCommand command) {
        return new Order(
            null, // orderId will be generated by the persistence layer
            command.getUserId(),
            command.getOrderItems(),
            command.getTotalPrice(),
            command.getStatus()
        );
    }
}
