package com.mercado_challenge.MercadoAdventure.domain.model;

import java.util.List;

import com.mercado_challenge.MercadoAdventure.application.port.in.command.UserRegisterCommand;
import com.mercado_challenge.MercadoAdventure.application.port.in.command.UserUpdateCommand;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    private String userId;
    private String name;
    private String email;
    private String password;
    private String address;
    private List<UserRole> userType;

    public static User createFromCommand(UserRegisterCommand command) {
        return new User(
            null, // userId will be generated by the persistence layer
            command.getName(),
            command.getEmail(),
            command.getPassword(),
            command.getAddress(),
            command.getUserType()
            );
    }

    public void updateFromCommand(UserUpdateCommand command) {
        if (command.getName() != null) {
            this.name = command.getName();
        }
        if (command.getEmail() != null) {
            this.email = command.getEmail();
        }
        if (command.getPassword() != null) {
            this.password = command.getPassword();
        }
        if (command.getAddress() != null) {
            this.address = command.getAddress();
        }
        if (command.getUserType() != null) {
            this.userType = command.getUserType();
        }
    }

}
